name: 'Build, Test, and Deploy'
'on':
  push:
    branches:
      - master
  pull_request: null

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.41.0-jammy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js with cache
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Cache Astro build
        uses: actions/cache@v4
        with:
          path: |
            .astro
            node_modules/.astro
            node_modules/.vite
          key: ${{ runner.os }}-astro-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-astro-${{ hashFiles('**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-astro-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        id: build
        run: pnpm run build

      - name: Run tests
        id: tests
        run: pnpm run test:e2e:run

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
          retention-days: 7
          
      - name: Deploy to Cloudflare Workers
        if: github.ref == 'refs/heads/master'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: '${{ secrets.CLOUDFLARE_API_TOKEN }}'
          accountId: '${{ secrets.CLOUDFLARE_ACCOUNT_ID }}'
          environment: production
